name: Release Atuin

on:
  workflow_dispatch:
    inputs:
      atuin_tag:
        description: "Atuin release tag to build (e.g., 18.3.0)"
        required: true
        type: string
defaults:
  run:
    shell: msys2 {0}

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: UCRT64
      - name: sanitize inputs
        env:
          ATUIN_TAG: ${{ inputs.atuin_tag }}
        run: |
          [[ "${ATUIN_TAG}" == ${ATUIN_TAG//[^0-9\.v]} ]] || exit 1
      - run: pacman --noconfirm -Syu mingw-w64-ucrt-x86_64-rust mingw-w64-ucrt-x86_64-protobuf # protobuf is needed by atuin
      - uses: Swatinem/rust-cache@v2
      - run: pwd
      - run: ./fetch_and_build.sh
        env:
          ATUIN_TAG: ${{ inputs.atuin_tag }}
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "v${ATUIN_TAG}" \
            --title "Atuin $ATUIN_TAG" \
            --notes "Automated build of Atuin $ATUIN_TAG for Windows" \
            $ATUIN_RELEASE_BIN_PATH
